name: KiCad Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t kicad-processing .

    - name: Run Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}/docs:/ws/docs kicad-processing

    - name: Commit and push changes
      run: |
        git checkout -b kicad-workflow
        git add docs
        git commit -m "Update docs with generated files"
        git push -f origin kicad-workflow
